server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/template?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456